nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.0.cjs
npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: ${FONT_AWESOME_AUTH_TOKEN}